import React from 'react'

import { Link } from "react-router-dom";

export default function PrivacyPolicy() {
    return (
        <div class="m-auto pb-10 pt-16 p-2 max-w-screen-lg">
            <p class="p-10 font-bold text-3xl md:text-5xl mt-2 text-center"> Privacy Policy </p>
            <div class="flex pb-6">
                <div class="m-auto p-2">
                    <p> Welcome to <b>creative-arcades.com</b>. <b>Creative Arcades</b> provides website features and other products and services to you when you visit or shop at <b>Creative Arcades</b>. <b>Creative Arcades</b> grants you access to its website <b>www.creative-arcades.com</b> (“Site”), conditioned on your acceptance of these terms, conditions and notices contained herein (“Terms of Use”). </p>
                    <br></br>
                    <p> Acceptance of Terms PLEASE READ THESE TERMS OF USE AND <b>CREATIVE ARCADES</b> PRIVACY POLICY CAREFULLY. BY USING THE SITE, YOU AGREE TO THESE TERMS OF USE, AND YOU CONSENT TO THE COLLECTION, USE AND DISCLOSURE OF INFORMATION AS DESCRIBED IN THESE TERMS OF USE AND OUR PRIVACY POLICY. IF YOU DO NOT AGREE TO THESE TERMS OF USE AND THE TERMS AND CONDITIONS OF OUR PRIVACY POLICY, YOU MUST EXIT THE SITE IMMEDIATELY AND DISCONTINUE ANY USE OF THE SITE AND ANY OF THEIR CONTENT. YOUR USE OF THE SITE SHALL BE DEEMED TO BE YOUR AGREEMENT TO ABIDE BY EACH OF THE TERMS SET FORTH BELOW. CREATIVE ARCADES CAN CHANGE THESE TERMS AT ANY TIME AND WITHOUT NOTICE. IF ANY MODIFICATION IS UNACCEPTABLE TO YOU, YOU SHALL CEASE USING THE SITE. IF YOU DO NOT CEASE USING THIS SITE, YOU WILL BE DEEMED TO HAVE ACCEPTED THE CHANGE. You are also subject to the <b>Creative Arcades’</b> Privacy Policy. </p>
                    <p class="sm:text-xl font-bold mt-10 mb-4"> Use and Restrictions </p>
                    <p> The Site may be accessed and used only by individuals who can form legally binding contracts under applicable laws, who are 18 years of age or older, and who are not barred from using the Site under applicable laws. The Site is provided solely as a convenience to you for non-commercial use. You may access and use the Site only in accordance with all applicable laws and regulations and with these Terms of Use. You acknowledge and agree that <b>Creative Arcades</b>, in its sole discretion and without notice or any further obligation to you, may temporarily suspend or permanently discontinue and refuse any and all current and future, access to or use of the Site. </p>
                    <p class="sm:text-xl font-bold mt-10 mb-4"> Reviews, Comments, Communications, and Other Content </p> 
                    <p> Visitors may post reviews, comments, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of “spam.” You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin content. <b>Creative Arcades</b> reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content. </p>
                    <br></br>
                    <p> If you do post content or submit material, and unless we indicate otherwise, you grant <b>Creative Arcades</b> a nonexclusive, royalty-free, perpetual, irrevocable, and fully sub-licensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant <b>Creative Arcades</b> and sublicenses the right to use the name that you submit in connection with such content. You represent and warrant that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify <b>Creative Arcades</b> for all claims resulting from content you supply. <b>Creative Arcades</b> has the right but not the obligation to monitor and edit or remove any activity or content. <b>Creative Arcades</b> takes no responsibility and assumes no liability for any content posted by you or any third party. </p>
                    <p class="sm:text-xl font-bold mt-10 mb-4"> Feedback </p>
                    <p> If you submit any feedback or ideas about our products and services to the Site, you hereby assign and agree to assign to <b>Creative Arcades</b> all right, title and interest in and to such feedback. </p>
                    <p class="sm:text-xl font-bold mt-10 mb-4"> Modifications </p>
                    <p> Any Content offered or posted on the Site is subject to modification or discontinuation at any time and from time to time without notice or obligation to you. Without limiting the foregoing, <b>Creative Arcades’</b> reserves the right, in its sole discretion, to charge fees for the use or purchase of, or access to, any products, services or Content offered through the Site, at any time and from time to time. </p>
                    <p class="sm:text-xl font-bold mt-10 mb-4"> Indemnification </p>
                    <p> You agree to defend, indemnify and hold harmless <b>Creative Arcades</b>, its affiliates and their respective directors, officers, employees and agents against any losses, liabilities, claims, expenses (including attorney’s fees) arising out of your account, your use of the Site, and your Submissions and any Personal Rights contained therein. </p>
                    <p class="sm:text-xl font-bold mt-10 mb-4"> Risk of Loss </p>
                    <p> All items purchased from <b>Creative Arcades</b> are made pursuant to a shipment contract. This means that the risk of loss and title for such items pass to you upon our delivery to the carrier. </p>
                    <br></br>
                    <p> Limitation of Liability <b>CREATIVE ARCADES</b> AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, LICENSORS AND THIRD PARTY PARTNERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL, EXEMPLARY, MULTIPLIED OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR REVENUES OR FAILURE TO REALIZE EXPECTED SAVINGS, OR ANY DAMAGES WHATSOEVER, WHETHER OR NOT SUCH PARTY HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, WHETHER UNDER CONTRACT, TORT (INCLUDING NEGLIGENCE) OR ANY OTHER THEORY, INCLUDING, WITHOUT LIMITATION, ARISING OUT OF OR IN CONNECTION WITH ANY LOSS OR OTHER DAMAGES IN CONNECTION WITH ANY UNAVAILABILITY OR NONPERFORMANCE OF THE SITE, ERRORS, OMISSIONS, VIRUSES AND MALICIOUS CODE. THESE LIMITATIONS WILL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. Certain laws do not allow limitations on implied warranties or conditions, or the exclusion or limitation of certain damages. If these laws apply, some or all of the above disclaimers, exclusions, or limitations, may not apply to you, and you may have additional rights to those contained herein. </p>
                    <p class="sm:text-xl font-bold mt-10 mb-4"> Governing Law </p>
                    <p> You agree that the laws of the state of California, without regard to principles of conflict of laws, will govern these Conditions of Use and any dispute of any sort that might arise between you and <b>Creative Arcades</b>. </p>
                    <p class="sm:text-xl font-bold mt-10 mb-4"> Miscellaneous </p>
                    <p> If any provision of these Terms of Use is held to be invalid, illegal or unenforceable in any respect under any applicable law or rule in any jurisdiction, such invalidity, illegality or unenforceability will not affect the effectiveness or validity of any provision in any other jurisdiction, and these Terms of Use will be reformed, construed and enforced in such jurisdiction as if such provision had never been contained herein. Any headings or titles herein are for convenience only. The official language of these Terms of Use exclusively shall be, and all communications and agreements between <b>Creative Arcades</b> and you and any proceedings in connection with these Terms of Use and/or your use of the Site, exclusively shall be made in, the English language. <b>Creative Arcades</b> and you waive any rights we may have under any other law to have these Terms of Use written in another language, and any translation of this Terms of Use will be for convenience only. You agree that no joint venture, partnership, employment, or agency relationship exists between you and <b>Creative Arcades</b> as a result of these Terms of Use, our Privacy Policy or any use of the Site. <b>Creative Arcades</b> performance of these Terms of Use is subject to existing laws and legal process, and nothing contained in these Terms of Use or our Privacy Policy is in derogation of <b>Creative Arcades</b> right to comply with law enforcement requests or requirements relating to your use of the Site or information provided to or gathered by <b>Creative Arcades</b> with respect to such use. These Terms of Use and our Privacy Policy constitute the entire agreement between you and <b>Creative Arcades</b> with respect to the Site, and they supersede all prior or contemporaneous communications and proposals, whether electronic, oral or written, between you and <b>Creative Arcades</b> with respect to the Site. </p>
                    <p class="sm:text-xl font-bold mt-10 mb-4"> Welcome to Radar for Fraud Teams </p>
                    <p> We use Stripe for payment, analytics, and other business services. Stripe collects identifying information about the devices that connect to its services. Stripe uses this information to operate and improve the services it provides to us, including for fraud detection. You can learn more about Stripe and read its privacy policy at <a class="hover:underline" href="http://stripe.com/privacy." target="_none">https://stripe.com/privacy</a>. </p>
                </div>
            </div>
        </div>
    );
}